### ISSUE TITLE
Automate

### ISSUE THREAD

**Issue by 22lane5** [arkalim/kindle-to-notion#1]
Hi!
I was wondering if there is a way to automate the syncing process where every time you plug in your kindle and type a single command the clippings file gets replaced and it syncs.

**Comment by rodbv** [comment]
Hi! I wonder if you've considered getting the highlights from https://read.amazon.com/notebook? This way it wouldn't be necessary to connect the Kindle to the computer which would make it possible to run it as a scheduled task, cron job etc.
The downside is that it would rely on web scraping which can change more often than their db inside the Kindle.

**Comment by arkalim** [comment]
Hi, this sounds good but does it work for books downloaded outside the
Amazon store and mailed to kindle by us?

**Comment by philffm** [comment]
![image](https://user-images.githubusercontent.com/6079545/183268412-232ae67c-7655-4475-b56a-fa622b88cd29.png)

![image](https://user-images.githubusercontent.com/6079545/183268416-8b591f00-fd6a-4982-85e2-842ca001e39b.png)

Mine is at least half automated (via. macOS shortcuts). But let me know if you found an easy way of detecting when the Kindle was plugged in

**Comment by philffm** [comment]
> Hi! I wonder if you've considered getting the highlights from [https://_read_.amazon.com/notebook](https://read.amazon.com/notebook)? This way it wouldn't be necessary to connect the Kindle to the computer which would make it possible to run it as a scheduled task, cron job etc. The downside is that it would rely on web scraping which can change more often than their db inside the Kindle.

https://github.com/lg08/kindle_notion_syncer
Looks like lg08 solved it that way in his repo :) Unfortunately (or thankfully privacy-wise) Amazon Reader doesn't include private documents.
