### ISSUE TITLE
Docker image not working on Apple M1 chipset

### ISSUE THREAD

**Issue by anuraagdjain** [arkalim/kindle-to-notion#16]
Try to run the setup command as mentioned in the README.md and I get the below error. 

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

```

Can you publish an image for arm platform too?

**Comment by arkalim** [comment]
This is a warning: it should run as the docker daemon runs on Rosetta emulation. Are your highlights getting synced?
