### ISSUE TITLE
API token is invalid

### ISSUE THREAD

**Issue by HaiderHB** [arkalim/kindle-to-notion#18]
It tells me my API token is invalid.

![image](https://user-images.githubusercontent.com/67211098/217732822-f3f400ce-9c1f-42db-a19f-bb2611b2de00.png)

The integration is added to the database and I provided the correct IDs for both of them

**Comment by SHaiderX** [comment]
Even running it in WSL gives me this:
![image](https://user-images.githubusercontent.com/67211098/217414708-2a3d7c1b-2228-4d1f-b665-00d3549271a0.png)

**Comment by arkalim** [comment]
You can use the GitHub Workflow now.
