### ISSUE TITLE
Docker Commands not functioning

### ISSUE THREAD

**Issue by cwrighta7xx** [arkalim/kindle-to-notion#20]
![image](https://user-images.githubusercontent.com/62577290/224219271-878a29f9-f937-4f27-98d2-d10c6f8bb4f9.png)

I am getting all sorts of errors when running the commands specified in the readme. I am running Windows 10 with Docker installed. Does anyone have tips for how to enter the docker commands in powershell without throwing errors?

**Comment by arkalim** [comment]
I guess you are missing `\` at the end of the second last line.

**Comment by cwrighta7xx** [comment]
This the \ does not seem to be the problem. The very first line is not recognized as a valid Docker command when I run it:

![image](https://user-images.githubusercontent.com/62577290/224460088-db97e332-179f-4142-b476-3fb7f630e973.png)

Any ideas?

**Comment by anuraagdjain** [comment]
@cwrighta7xx try the below command. It should work. In the second last line **\** was missing

```
C: \Users \ Caleb\ kindle-to-notion> docker run - -rm -d \
-v C: \Users\ Caleb\ Desktop\ Reading Notes \My Clippings.txt: /code/resources/My\ Clippings.txt \
-v cache: /code/cache \
-e NOTION_API_KEY=secret_8Yla7ftCVi4AAGPYD2iLFVGf9JU4VnDDK4wnw6gwEHZ \
-e BOOK_DB_ID=af8c86289de5460bb4fe7730649501a0 \
gher.io/arkalim/kindle-to-notion:master
```

**Comment by arkalim** [comment]
You can just use GitHub workflows now. No need to run docker commands locally.
