### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by brigante88** [arkalim/kindle-to-notion#23]
Hi, nothing is synchronized. I noticed that I get this error on github: "Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files."
<img width="1117" alt="Screenshot 2023-05-03 alle 23 28 17" src="https://user-images.githubusercontent.com/50744428/236227319-68f9764f-39e8-4dc6-b391-5f23abdb9295.png">

**Comment by arkalim** [comment]
Can you show the logs of the runner?

**Comment by brigante88** [comment]
thanks
[logs_8.zip](https://github.com/arkalim/kindle-to-notion/files/11407894/logs_8.zip)

**Comment by arkalim** [comment]
Can you try deleting the `sync.json` file and re-running the workflow?

**Comment by brigante88** [comment]
> Can you try deleting the `sync.json` file and re-running the workflow?
the problem remains.

But could it be that the problem is due to the My Clippings.txt file which is in Italian?

**Comment by arkalim** [comment]
Can you share your clippings file? If the highlights is in Italian, it shouldn't be a problem. But if the clippings language is in Italian, it won't work.

**Comment by brigante88** [comment]
[My Clippings.txt](https://github.com/arkalim/kindle-to-notion/files/11412471/My.Clippings.txt)

**Comment by arkalim** [comment]
I see that your clippings file is in Italian. The app doesn't support that yet. Would it be possible for you to write regex for parsing Italian clippings? If so, you can do so and create a pull request.
