### ISSUE TITLE
Not syncing all books

### ISSUE THREAD

**Issue by Clayjoelo** [arkalim/kindle-to-notion#24]
The code only works with books that were purchased through Amazon, it doesn't sync PDFs.

**Comment by arkalim** [comment]
It works only with books used in `.mobi` format. You can download books online from LibGen and use them too. They will work with this app.

**Comment by Clayjoelo** [comment]
Thanks, I am just going to convert my PDFs into .mobi format now though. Have a great day

**Comment by brookekelseyryan** [comment]
> It works only with books used in `.mobi` format. You can download books online from LibGen and use them too. They will work with this app.

Will this work for new books added to Kindle? Apparently they’re not supporting sending .mobi to the Kindle anymore https://www.amazon.com/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA#:~:text=Note%3A%20Beginning%20in%20early%202023,still%20read%20them%20with%20Kindle.
Will this app work for epub files?

**Comment by arkalim** [comment]
As far as I know, as long as Kindle supports the book file (whether in `.mobi` or `.epub`), the highlight format should be the same.

**Comment by Glaukon847** [comment]
I would like to know why some books did not appear in the notion
