### ISSUE TITLE
Syncing notes as well as highlights

### ISSUE THREAD

**Issue by matthewmcclatchie** [arkalim/kindle-to-notion#29]
Hi, 

Thanks for this, it works great in my experience so far!

Less an issue, more a question... any plans to include notes, along with highlights?

I tested this out today and found that, whilst the notes are present in the MyClippings.txt file, they didn't appear in Notion after sync. I couldn't see any reference to notes in the codebase when I had a brief look, so assuming this isn't part of the functionality, but wondered if it might be in future?

Thanks!

**Comment by arkalim** [comment]
Hi @matthewmcclatchie, thanks for the kind words. Can you please share your `MyClippings.txt` file that has notes? I'll try to modify the app to sync notes too.

**Comment by matthewmcclatchie** [comment]
Of course!

As you can see, it only contains a single test highlight and note.

[My Clippings.txt](https://github.com/arkalim/kindle-to-notion/files/11616314/My.Clippings.txt)

**Comment by arkalim** [comment]
I've updated the regex to consider notes too.

**Comment by matthewmcclatchie** [comment]
Awesome! Works perfectly, thank you!
