### ISSUE TITLE
No match for regex of clippings

### ISSUE THREAD

**Issue by manigandan-dorairaj** [arkalim/kindle-to-notion#3]
Hi,

Thanks a lot for this tool! It's super cool.

Found a small issue (may be due to my Kindle Paperwhite version) and resolution. 

The clippings are in a **different format** than the one used in this code.

Eg.
'=======
﻿Kindle Paperwhite User's Guide, 3rd Edition (Amazon)
- Your Highlight at location 347-348 | Added on Wednesday, 28 June 2017 22:45:15

tap the sides of the screen. To exit Kindle
'=======

Key differences in the format are:

- on Location vs at location
- Month dd, yyy HH:mm:ss AM/PM vs dd Month yyyy HH:mm:ss (24Hr format)
- CR and line-breaks after date and time

I have replaced the regex code with the below, and it worked.

`/(.+) \((.+)\)\r*\n- Your Highlight (at|on) (location|Location|page)( |(.+))([0-9]+)-([0-9]+) \| Added on ([a-zA-Z]+), ([0-9]+) ([a-zA-Z]+) ([0-9]{4}) ([0-9]+):([0-9]+):([0-9]+)\r*\n\r*\n(.+)/gm`

Maybe if you can modify the Regex to match the above example too, it would help.

Thanks

**Comment by arkalim** [comment]
Thanks for reaching out, can you please raise a pull request with the
necessary changes?

Regards

**Comment by manigandan-dorairaj** [comment]
Hi,

Sure , will do that.

Thanks

**Comment by manigandan-dorairaj** [comment]
Submitted PR. Please review and merge. Thanks.

**Comment by arkalim** [comment]
Done ✅

**Comment by arkalim** [comment]
Thanks for the contribution
