### ISSUE TITLE
Issues with Syncing

### ISSUE THREAD

**Issue by Omama75** [arkalim/kindle-to-notion#39]
Hi, after following your Yt tutorial I sadly still have issues... 
my Workspace key looks a bit different, but I took the 32char code between library- and the ?

still I get an error : Failed to sync highlights APIResponseError: Could not find database with ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

https://www.notion.so/[workspacename]/Library-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?pvs=x

(ofc instead of xxx there is the "real" key)

Do you have any ideas why I get this issue?
Best regards

**Comment by cccruzr** [comment]
@Omama75 I was able to debug this by opening the database as full page and copying its ID.

![image](https://github.com/arkalim/kindle-to-notion/assets/24302565/14e5755d-6001-447a-bdad-8cec9172233b)

@arkalim maybe it's time to update the tutorial?

**Comment by arkalim** [comment]
@cccruzr Thanks for the update. I'll update the README instructions.

**Comment by LGiu** [comment]
I'm having the same problem and I don't find a solution
