### ISSUE TITLE
Problem when using "My Clippings.txt"

### ISSUE THREAD

**Issue by matheusmstos** [arkalim/kindle-to-notion#6]
In the end of the process, where it says

> Connect your Kindle to your computer. Navigate to Kindle arrow_right documents and copy My Clippings.txt. Replace my My Clippings.txt in resources folder with yours.

After doing it, running `npm start`, I get:

![image](https://user-images.githubusercontent.com/18218843/182624986-8b5346be-5540-48aa-afa1-fb4ae50ecb7a.png)

No books and no clipping have been imported as a result. I've tested with the Clippings that came in the resources folder, and it worked. So, I have no ideia what is happening...

Maybe it has something to do with this:

![image](https://user-images.githubusercontent.com/18218843/182692834-87958363-f1d4-4fb6-b02a-f3bef7726fb7.png)

Apparently, the clippings from my kindle it's not a plain/text file and maybe thats whats happening.  

[My Clippings.txt](https://github.com/arkalim/kindle-to-notion/files/9254437/My.Clippings.txt)

**Comment by ay-rod** [comment]
I had this same bug. After a bit of trial and error, it seems like the error for me was the regex that looks for the date. It seems the regex in parser.ts looks for an AM / PM value, whereas my kindle was set to 24hrs so displayed time without AM or PM. 

After I removed that part of the regex everything worked perfectly for me. 
`private regex =
    /(.+) \((.+)\)\r*\n- Your Highlight (at|on) (location|Location|page)( |(.+))([0-9]+)-([0-9]+) \| Added on ([a-zA-Z]+), ([a-zA-Z]+|[0-9]+) ([0-9]+|[a-zA-Z]+),? ([0-9]{4}) ([0-9]+):([0-9]+):([0-9]+\s?)\r*\n\r*\n(.+)/gm;`

**Comment by kaarelkaarelson** [comment]
Thanks, @netswift2905! Your solution worked for me.

Please make a pull request with same code! Otherwise, all the people who have **English (United Kingdom)** language setting (or other 24H time language) won't be able to use this app. I believe, @arkalim will approve it.

**Comment by michaldolnik** [comment]
Thanks as well! @netswift2905 

It fixed my problem!

**Comment by mikaal46** [comment]
@netswift2905 I applied your fix and then put in the "npm start" command and it looked like it was working but then I got the following error:

@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one:\n' +
    'body.children.length should be ≤ `100`, instead was `197`.\n' +
    'body.parent.page_id should be defined, instead was `undefined`.'
}

Can you please guide as what this is and what needs to be done? Also, I know very little about coding. Thanks.
