### ISSUE TITLE
Highlights not updating

### ISSUE THREAD

**Issue by philffm** [arkalim/kindle-to-notion#7]
![Screenshot 2022-08-07 at 02 47 49](https://user-images.githubusercontent.com/6079545/183270481-a1deeb8a-2765-4431-9dab-7e511c418d3d.png)
![Screenshot 2022-08-07 at 02 49 39](https://user-images.githubusercontent.com/6079545/183270482-42e9d29e-23bf-4956-b2c2-6b63c82905b4.png)
![Screenshot 2022-08-07 at 02 48 33](https://user-images.githubusercontent.com/6079545/183270484-07fcfe47-7034-4501-8efa-5744d81165bd.png)

Good morning,

what a great project. Thanks for your work :)

Unfortunately the updating of highlights does not work (Looks like it does not read the updated My Clippings file properly)

Do you have an idea :)?

Cheers, Phil

**Comment by ay-rod** [comment]
I had this same bug. After a bit of trial and error, it seems like the error for me was the regex that looks for the date. It seems the regex in parser.ts looks for an AM / PM value, whereas my kindle was set to 24hrs so displayed time without AM or PM.

After I removed that part of the regex everything worked perfectly for me.
`private regex =
    /(.+) \((.+)\)\r*\n- Your Highlight (at|on) (location|Location|page)( |(.+))([0-9]+)-([0-9]+) \| Added on ([a-zA-Z]+), ([a-zA-Z]+|[0-9]+) ([0-9]+|[a-zA-Z]+),? ([0-9]{4}) ([0-9]+):([0-9]+):([0-9]+\s?)\r*\n\r*\n(.+)/gm;`

**Comment by philffm** [comment]
@netswift2905 Awesome, thanks a lot - working great :)
