### ISSUE TITLE
Parse HTML format

### ISSUE THREAD

**Issue by ArtemSerga** [arkalim/kindle-to-notion#8]
Hello @arkalim. A really great work 👍
I'm wondering are you going to support HTML export format https://www.easeus.com/knowledge-center/export-kindle-highlights.html#kindle_mobile_app ?

HTML format benefits comparing to Clippings.txt
- Heading sections
- Highlight color

**Comment by arkalim** [comment]
Hi @ArtemSerga,

That's a good idea. Can you make the changes and raise a pull request?
